name: RSS Check

on:
  schedule:
    - cron: '*/30 * * * *'  # 每30分钟运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-rss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xmlstarlet
        if ! command -v jq &> /dev/null; then
          sudo apt-get install -y jq
        fi

    - name: Set up environment variables
      run: |
        echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> $GITHUB_ENV
        echo "TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}" >> $GITHUB_ENV

    - name: Run RSS check script
      run: |
        chmod +x ./rss_check.sh
        ./rss_check.sh

    - name: Commit and push if there are changes
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add rss_cache.txt
        git commit -m "Update RSS cache" || echo "No changes to commit"
        git push

