name: RSS Check

on:
  schedule:
    - cron: '0 */1 * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  check-rss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xmlstarlet curl jq

    - name: Run RSS check script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        chmod +x ./rss_check.sh
        ./rss_check.sh

    - name: Commit and push cache
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add rss_cache.txt
        git commit -m "Update RSS cache" || echo "No changes to commit"
        git push https://${{ secrets.PAT }}@github.com/whu1233334/clash.git HEAD:master
