name: Check RSS and Send Telegram Notifications

on:
  schedule:
    - cron: '0 */1 * * *'  # 每小时运行一次
  workflow_dispatch:  # 允许手动触发

permissions:
  contents: write

jobs:
  check-rss:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xmlstarlet curl jq

    - name: Run RSS check script
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        chmod +x ./rss_check.sh
        ./rss_check.sh

    - name: Commit and push if cache file changed
      run: |
        git config --global user.name 'GitHub Action'
        git config --global user.email 'action@github.com'
        git add rss_cache.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update RSS cache" && git push)
